"""Constants for Hassenger."""

DOMAIN = "hassenger"
INTEGRATION_VERSION = "1.0.0"
STORAGE_KEY = "hassenger.messages"
STORAGE_VERSION = 1
EVENT_UPDATED = "hassenger_updated"
EVENT_MESSAGE_SENT = "hassenger_message_sent"
DATA_STORE = "store"
MAX_MESSAGE_LENGTH = 4000
MAX_THREAD_TITLE_LENGTH = 120
MAX_THREAD_ID_LENGTH = 128
MAX_SENDER_NAME_LENGTH = 120
MAX_PARTICIPANTS = 50
MAX_ICON_LENGTH = 100
MAX_COLOR_LENGTH = 32
MAX_ATTACHMENT_REFERENCE_LENGTH = 4096
MAX_ATTACHMENT_NAME_LENGTH = 255
MAX_PRESENCE_MESSAGE_LENGTH = 160
MAX_TIMESTAMP_LENGTH = 64
MAX_MEDIA_FILE_SIZE = 10 * 1024 * 1024
MAX_MEDIA_TOTAL_SIZE = 100 * 1024 * 1024
MEDIA_SUBDIRECTORY = "hassenger"
DEFAULT_RETENTION_DAYS = 365
