name: Validate HACS and Hassfest

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
  hassfest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: home-assistant/actions/hassfest@master
